spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://agarwalshaan27:g5p3vCbP1ZbcsdCX@cluster0.vtjmyy6.mongodb.net/backend?retryWrites=true&w=majority

server:
  port: 8080